### ISSUE TITLE
执行脚本错误

### ISSUE THREAD

**Issue by ghost** [se4/SSR-ML-Docker#1]
': not a valid identifierne 3: export: `PATH

: command not foundsh: line 12: 

: command not foundsh: line 13: clear

: command not foundsh: line 14: echo

: command not foundsh: line 15:
 
: command not foundsh: line 16: echo

: command not foundsh: line 17:
 
'nekey_install_ssr.sh: line 27: syntax error near unexpected token `{

'nekey_install_ssr.sh: line 27: `function rootness(){

centos 6.5

**Comment by 6r6** [comment]
请再试试一键脚本:在手机(或windows)上编辑的时候空行为PC下的空行，**空行方式**选择成**UNIX**空行即可

**Comment by 6r6** [comment]
先执行`rm onekey_install_ssr.sh`，删除之前缓存的文件，再重新`wget -N --no-check-certificate https://raw.githubusercontent.com/se4/SSR-ML-Docker/master/onekey_install_ssr.sh && chmod +x *.sh && bash onekey_install_ssr.sh`，不然系统默认执行之前下载的脚本
