### ISSUE TITLE
关于协议和混淆参数设置

### ISSUE THREAD

**Issue by yunyu950908** [se4/SSR-ML-Docker#2]
请教一下SSR的协议类型、协议参数以及混淆类型、混淆参数怎样设置？如何获取到符合自己需求的参数？

**Comment by 6r6** [comment]
请试试修改启动参数：端口号、混淆类型都是可以直接在docker启动指令里指定的。
如果需要免流， 相关参数需要自行抓包测试的，或者去恩山论坛找大神抓好的。
