### ISSUE TITLE
能问下怎么清除github上的所有文件的。

### ISSUE THREAD

**Issue by zeromake** [se4/SSR-ML-Docker#3]
如题。
我看commit里所有的文件改动都没了。

**Comment by 6r6** [comment]
方法应该有很多，我使用的是java编写的一个清理工具，名为
BFG Repo-Cleaner
http://rtyley.github.io/bfg-repo-cleaner/

请在电脑上安装java运行环境并配置好运行变量。
主页上有相关的使用方法，我这里提供一下详细的过程：

先克隆到本地：
`git clone --mirror https://github.com/se4/SSR-ML-Docker.git`

进入bfg.jar所在的文件夹，然后我想清理Dockerfile这个文件的所有记录：
`java -jar bfg.jar --delete-folders Dockerfile --delete-files Dockerfile  --no-blob-protection  SSR-ML-Docker.git`

当然也可以完整清理名为Manyuser的整个文件夹：
`java -jar bfg.jar --delete-folders Manyuser --delete-files Manyuser  --no-blob-protection  SSR-ML-Docker.git`

进入项目文件夹：
`cd SSR-ML-Docker.git`

提交你的更改：
`git reflog expire --expire=now --all && git gc --prune=now --aggressive`
`git push`

**Comment by zeromake** [comment]
@se4 谢谢知道了
